Repository asciidoctor/asciidoctor-gradle-plugin, pull requests merged in 2019-06, with the labels that each got.

#407 fix two typos in the README
  README.adoc
Labels: 2.x

#397 Fix version of bibtex-ruby to 4.4.7 for test purposes
  asciidoctor-gradle-jvm-gems/src/gradleTest/external-gems/build.gradle
Labels: 2.x, infrastructure

#406 Configurations can be supplied via Provider instances
  asciidoctor-gradle-jvm-gems/src/gradleTest/external-gems/build.gradle
  asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy
  asciidoctor-gradle-jvm/src/test/groovy/org/asciidoctor/gradle/jvm/AsciidoctorTaskSpec.groovy
  config/codenarc/codenarc.groovy
Labels: 2.x

#409 Added a test case for EPUB for linked chapters (#408)
  README.adoc
  asciidoctor-gradle-jvm-epub/src/intTest/groovy/org/asciidoctor/gradle/jvm/epub/LinkedChaptersFunctionalSpec.groovy
  asciidoctor-gradle-jvm-epub/src/intTest/projects/issue-409-link-regression/src/docs/asciidoc/chapter1.adoc
  asciidoctor-gradle-jvm-epub/src/intTest/projects/issue-409-link-regression/src/docs/asciidoc/chapter2.adoc
  asciidoctor-gradle-jvm-epub/src/intTest/projects/issue-409-link-regression/src/docs/asciidoc/epub3.adoc
  module-versions.properties
Labels: 3.x

#413 EPUB linked chapters test
  asciidoctor-gradle-jvm-epub/src/intTest/groovy/org/asciidoctor/gradle/jvm/epub/LinkedChaptersFunctionalSpec.groovy
  asciidoctor-gradle-jvm-epub/src/intTest/projects/issue-409-link-regression/src/docs/asciidoc/chapter1.adoc
  asciidoctor-gradle-jvm-epub/src/intTest/projects/issue-409-link-regression/src/docs/asciidoc/chapter2.adoc
  asciidoctor-gradle-jvm-epub/src/intTest/projects/issue-409-link-regression/src/docs/asciidoc/epub3.adoc
Labels: 2.x

#418 Asciidoctor dependency reports on a per-task basis (2.x)
  asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy
  asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJBasePlugin.groovy
Labels: 2.x

#419 Report dependencies for any Asciidoctor task (#393)
  asciidoctor-gradle-base/src/main/groovy/org/asciidoctor/gradle/base/AbstractAsciidoctorBaseTask.groovy
  asciidoctor-gradle-base/src/main/groovy/org/asciidoctor/gradle/base/AsciidoctorBasePlugin.groovy
  asciidoctor-gradle-base/src/main/groovy/org/asciidoctor/gradle/base/internal/ConfigurationUtils.groovy
  asciidoctor-gradle-base/src/test/groovy/org/asciidoctor/gradle/base/AsciidoctorBasePluginSpec.groovy
  asciidoctor-gradle-js/src/main/groovy/org/asciidoctor/gradle/js/nodejs/AbstractAsciidoctorNodeJSTask.groovy
  asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy
  asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJBasePlugin.groovy
  asciidoctor-gradle-jvm/src/test/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJBasePluginSpec.groovy
Labels: 3.x
