Repository asciidoctor/asciidoctor-gradle-plugin, pull requests merged in 2020-01, with the labels that each got.

#492 Add baseDirFollowsSourceFile() to restore support for include directive with relative path
  base/src/main/groovy/org/asciidoctor/gradle/base/AbstractAsciidoctorBaseTask.groovy
  base/src/main/groovy/org/asciidoctor/gradle/base/basedir/BaseDirIsNull.groovy
  docs/src/docs/asciidoc/parts/common-task-configuration.adoc
  jvm/src/intTest/groovy/org/asciidoctor/gradle/jvm/RelativeIncludeFunctionalSpec.groovy
  jvm/src/intTest/projects/relative-include/src/docs/asciidoc/nested/_nested-include.adoc
  jvm/src/intTest/projects/relative-include/src/docs/asciidoc/nested/sample.adoc
  jvm/src/test/groovy/org/asciidoctor/gradle/jvm/AsciidoctorTaskSpec.groovy
Labels: 3.x

#491 Use property objects for sourceDir and outputDir
  base/src/main/groovy/org/asciidoctor/gradle/base/AbstractAsciidoctorBaseTask.groovy
  base/src/main/groovy/org/asciidoctor/gradle/base/AsciidoctorUtils.groovy
  js/src/main/groovy/org/asciidoctor/gradle/js/nodejs/AsciidoctorTask.groovy
  jvm-epub/src/main/groovy/org/asciidoctor/gradle/jvm/epub/AsciidoctorEpubTask.groovy
  jvm-epub/src/main/groovy/org/asciidoctor/gradle/jvm/epub/AsciidoctorJEpubPlugin.groovy
  jvm-leanpub/src/main/groovy/org/asciidoctor/gradle/jvm/leanpub/AsciidoctorJLeanpubPlugin.groovy
  jvm-pdf/src/intTest/groovy/org/asciidoctor/gradle/jvm/pdf/AsciidoctorPdfTaskFunctionalSpec.groovy
  jvm-pdf/src/main/groovy/org/asciidoctor/gradle/jvm/pdf/AsciidoctorJPdfPlugin.groovy
  jvm-slides/src/main/groovy/org/asciidoctor/gradle/jvm/slides/AsciidoctorRevealJSPlugin.groovy
  jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorTask.groovy
Labels: 3.x

#496 Fix bug in AbstractAsciidoctorTask#sources(java.lang.String...)
  asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy
  asciidoctor-gradle-jvm/src/test/groovy/org/asciidoctor/gradle/jvm/BaseTaskPatternSpec.groovy
Labels: 2.x

#495 Fix bug in AbstractAsciidoctorBaseTask#sources(java.lang.String...)
  base/src/main/groovy/org/asciidoctor/gradle/base/AbstractAsciidoctorBaseTask.groovy
  base/src/test/groovy/org/asciidoctor/gradle/base/BaseTaskPatternSpec.groovy
Labels: 3.x

#498 Add "clearSources()" method to base task
  base/src/main/groovy/org/asciidoctor/gradle/base/AbstractAsciidoctorBaseTask.groovy
  base/src/test/groovy/org/asciidoctor/gradle/base/BaseTaskPatternSpec.groovy
Labels: 3.x, enhancement

#497 Allow slides and convert plugins to co-exist
  jvm-slides/src/intTest/groovy/org/asciidoctor/gradle/jvm/slides/AsciidoctorSlidesAndConvertPluginsCoexistFunctionalSpec.groovy
  jvm-slides/src/intTest/projects/coexist/src/docs/asciidoc/sample.asciidoc
  jvm-slides/src/intTest/projects/coexist/src/docs/slides/revealjs.adoc
  jvm-slides/src/main/groovy/org/asciidoctor/gradle/jvm/slides/AsciidoctorJRevealJSTask.groovy
Labels: 3.x

#503 fix some typos in the docs
  docs/src/docs/asciidoc/parts/common-task-configuration.adoc
Labels: 3.x, documentation

#501 resolves #500 slideNumber is a string
  docs/src/docs/asciidoc/parts/asciidoctorj-revealjs-plugin.adoc
  jvm-slides/src/gradleTest/basic-slides/build.gradle
  jvm-slides/src/main/groovy/org/asciidoctor/gradle/jvm/slides/RevealJSOptions.groovy
  jvm-slides/src/test/groovy/org/asciidoctor/gradle/jvm/slides/AsciidoctorRevealJSTaskSpec.groovy
  jvm-slides/src/test/groovy/org/asciidoctor/gradle/jvm/slides/RevealJSOptionsSpec.groovy
Labels: 3.x, enhancement

#514 Allow actions to be executed for asciidoctorj detached configuration
  docs/src/docs/asciidoc/appendix/tips-and-tricks.adoc
  jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJExtension.groovy
  jvm/src/test/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJExtensionSpec.groovy
Labels: 3.x, enhancement

#512 Don't add revnumber attr when project.version is unspecified
  base/src/main/groovy/org/asciidoctor/gradle/base/AbstractAsciidoctorBaseTask.groovy
  jvm/src/test/groovy/org/asciidoctor/gradle/jvm/AsciidoctorTaskSpec.groovy
Labels: 3.x, bug

#517 Copy resources prior to conversion (#493)
  jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy
Labels: 3.x

#513 Prepare 3.1.0 release
  README.adoc
  gradle.properties
Labels: 3.x

#518 Fix task name
  .github/workflows/build.yml
Labels: infrastructure

#521 Update contributor list
  gradle/publishing.gradle
Labels: 3.x, documentation

#519 3.1.0 Release
  README.adoc
  base/src/main/groovy/org/asciidoctor/gradle/base/AbstractAsciidoctorBaseTask.groovy
  docs/src/docs/asciidoc/appendix/tips-and-tricks.adoc
  gradle.properties
  gradle/publishing.gradle
  jvm/src/main/groovy/org/asciidoctor/gradle/internal/ExecutorConfiguration.groovy
  jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy
  jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJExtension.groovy
  jvm/src/remoteTest/groovy/org/asciidoctor/gradle/remote/internal/RemoteSpecification.groovy
  jvm/src/test/groovy/org/asciidoctor/gradle/internal/ExecutorConfigurationSpec.groovy
  jvm/src/test/groovy/org/asciidoctor/gradle/jvm/AsciidoctorJExtensionSpec.groovy
  jvm/src/test/groovy/org/asciidoctor/gradle/jvm/AsciidoctorTaskSpec.groovy
Labels: 3.x
